title: "Cale's Spatial Data Science Portfolio"
email: "cbherrera1@up.edu.ph"
description: "Welcome to my spatial data science portfolio!"
author: "Cale Andriane B. Herrera"
url: "https://Todorokeyl.github.io/portfolio"

# Theme configuration using remote theme
remote_theme: "pages-themes/hacker@v0.2.0"

# Social Links
social_links:
  - name: GitHub
    url: "https://github.com/Todorkeyl"
    icon: "fa-github"
  - name: LinkedIn
    url: "https://linkedin.com/in/cale-andriane-herrera-699758281"
    icon: "fa-linkedin"

# Additional options
plugins:
  - jekyll-remote-theme

# Navigation menu
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Markdown options
markdown: kramdown
highlighter: rouge

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
